###########################################
### Configuration file for EEG pipeline ###
###########################################

## GENERAL ##

# Name of the pipeline
pipeline_name: "pipeline01"

njobs: 3 # Max. number of concurent jobs
njobs2: 5 # Max. number of concurent jobs per participant

## CONVERSION ##

# Ids for original files (will only be used for conversion)
raw_ids: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
# Path of original files (will only be used for conversion)
raw_path: "/share/projects/mueller/Xmas_Oddballmatch/raw_biosemi/Xmas_{id:02d}.bdf"

# Root path for BIDS files structure
bids_root_path: "/share/tmpdata/pabst/xmasoddballmatch-bids"
# Name of the task
task_name: "xmasoddballmatch"

## PREPROCESSING ##

# Power line frequenciy (null to skip ZapLine)
line_freq: null

# Seed for PRNGs
random_state: 42

# Events
events_dict:
  random/0/deviant: 102
  random/1/standard: 111
  random/0/standard: 101
  random/2/standard: 121
  random/3/standard: 131
  random/4/standard: 141
  random/5/deviant : 152
  random/5/standard: 151
  random/nopattern/standard: 1
  random/nopattern/deviant: 2
  predictable/1/standard: 11
  predictable/2/standard: 21
  predictable/3/standard: 31
  predictable/4/standard: 41
  predictable/5/standard: 51
  predictable/5/deviant: 52
  begin: 65790
  end: 65536


## ICA ##
ica_l_freq: 2.0
ica_h_freq: 40.
ica_downsample_freq: 250.
ica_filter_method: firwin
ica_fir_window: hamming
ica_diff_criterion: 100e-10 # Delta criterion for epoch rejection

## FILTERING ##
filter_method: firwin
fir_window: hamming
l_freq: 0.1
h_freq: 30.0

## EPOCHING ##
epoch_window: !!python/tuple [-0.3, 0.3]
baseline_winow: !!python/tuple [-0.3, 0.0]
conditions_of_interest:
  - random/deviant
  - random/standard
  - predictable/4/standard
  - predictable/5/deviant
  - random/4/standard
  - random/5/deviant


## VIZ ##
main_colors:
  - "#024B79"
  - "#BA5800"
accent_colors:
  - "#43B7C2"
  - "#FFAD48"